### PR TITLE
Remove personal information

### PR DESCRIPTION
**Pull request by Sheenam3**

### CODE REVIEW

**Comment by mJace** [comment]
@Sheenam3 this PR failed to pass the CI. Could you check on this?

**Comment by Sheenam3** [comment]
```
go: downloading github.com/ITRI-ICL-Peregrine/x-tracer v0.0.0-20201028062226-d80b26e2e36e
cmd/x-tracer/x-tracer.go:5:2: module github.com/ITRI-ICL-Peregrine/x-tracer@latest found (v0.0.0-20201028062226-d80b26e2e36e), but does not contain package github.com/ITRI-ICL-Peregrine/x-tracer/database
cmd/x-tracer/x-tracer.go:6:2: module github.com/ITRI-ICL-Peregrine/x-tracer@latest found (v0.0.0-20201028062226-d80b26e2e36e), but does not contain package github.com/ITRI-ICL-Peregrine/x-tracer/events
cmd/x-tracer/x-tracer.go:7:2: module github.com/ITRI-ICL-Peregrine/x-tracer@latest found (v0.0.0-20201028062226-d80b26e2e36e), but does not contain package github.com/ITRI-ICL-Peregrine/x-tracer/pkg
cmd/x-tracer/x-tracer.go:8:2: module github.com/ITRI-ICL-Peregrine/x-tracer@latest found (v0.0.0-20201028062226-d80b26e2e36e), but does not contain package github.com/ITRI-ICL-Peregrine/x-tracer/ui
Makefile:34: recipe for target '/home/travis/gopath/src/github.com/ITRI-ICL-Peregrine/x-tracer/bin/x-tracer' failed
make: *** [/home/travis/gopath/src/github.com/ITRI-ICL-Peregrine/x-tracer/bin/x-tracer] Error 1
The command "make" exited with 2.
```

Seems like master branch is not merged with current develop branch and it still is not upto date with CUI version

**Comment by mJace** [comment]
Or could you provide the successful build log on your environment?
so I can accept this PR.

**Comment by Sheenam3** [comment]
Here is a successful build from my environment
https://travis-ci.com/github/Sheenam3/x-tracer-gocui/builds/202771075

**Pull request merged**
