### PR TITLE
makefile refactor

### PR DESCRIPTION
**Pull request by Sheenam3**
Fixed:
1. make (build x-tracer & x-agent)
2. make release
3. make publish

### CODE REVIEW

**Comment by mJace** [comment]
Need to
1. remove your docker hub ID in makefile. (We will tell user to set up env var for $NS in README.md later)
2. remove unnecessary comment-outs.

**Comment by mJace** [comment]
This PR fixes #2

**Comment by mJace** [comment]
LGTM

**Comment by mJace** [comment]
Reopen.

**Comment by Sheenam3** [comment]
@mJace Done with the following:

> Need to
> 
> 1. remove your docker hub ID in makefile. (We will tell user to set up env var for $NS in README.md later)
> 2. remove unnecessary comment-outs in the makefile.

**Pull request merged**
